solution: homelink
name: enrichment

serviceAccount: homelink-identity
port: 7200

extraLabels: {}
podAnnotations: {}
podLabels: {}

image:
  registry: aksmsclusteracr.azurecr.io
  pullPolicy: IfNotPresent

probes:
  startupPath: /mgt/startup-check
  readinessPath: /mgt/ready-check
  livenessPath: /mgt/health-check

gateway: 
  name: homelink-gateway
  hosts:
    - homelink.com